### ISSUE TITLE
L1 Mastering Font checklist 

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/lavishly-yours#3]
### L1 Mastering Font checklist

**Diacritics**
- [x] Inspect the font and choose the best version of the diacritics (in terms of balance, weight, size, contrast) and move them to comb mark.
- [x] Adjust left and right sidebearings of all the comb marks to 0.
- [x] Work on the selected diacritics to ensure the balance among all marks (contrast, weight, size, stroke or others)
- [x] Ensure the consistence among related marks, [see issue of reference](https://github.com/googlefonts/italianno/issues/6).
- [x] Adjust position, weight, or outlines of the diacritics if needed, without changing the design of them, and using glyphs app locked guidelines.
- [x] Decomposed transformed components, review proportions ensuring round coordinates.
- [x] Test the comb marks by inspecting all of them in context (right-click and choose all glyphs using this component).
- [x] Inspect and balance the below marks (size, weight, balance) e.g. `ogonek` `cedilla` to avoid huge marks
- [x] Create [Catalan Punt Volat ](https://glyphsapp.com/learn/localize-your-font-catalan-punt-volat)
- [x] Delete the legacy marks and add them back so they are made from comb marks.
- [x] Create comb.case marks by making them less tall and less narrow while keeping them at the same weight (preferable at the height they are intended to use, to be able to inspect them in their context)
- [x] Create the Vietnamese mark.
- [x] Make compound glyphs for the entire font.
- [x] Adjust the anchor position.

**Glyphs & Outlines**
- [x] Create the missing glyphs to cover the Latin Core and Plus GF encodings if they are easy to go cases. Otherwise, please report them to the designer in the Design Issue.
- [x] Inspect all the included glyphs has the Upper and Lowercase. 
- [x] Ensure the above item by inspecting there are no glyphs with double encodings (Uppers + lowercase)
- [x] Check kerning and spacing by using the .txt files. Fix any kerning and spacing critical cases (covering the most common kerning pairs).
- [x] Check spacing and kerning for numerals (main .lf .osf) and use arithmetic -key- spacing for the `.lf` ones
- [x] Check the spacing of terminal forms to avoid crashes or collisions. [Issue of reference](https://github.com/googlefonts/comforter/issues/7)
- [x] Run the automatic Glyphsapp command: `Resolve all metrics` to update the metrics in the entire font.
- [x] Check everything once again by going glyph by glyph.
- [x] Run the automatic Glyphsapp `Update Glyph Info` command to avoid bad names issues
- [x] `@` `¿?` `¡!` `””` `«»` position, spacing is good
- [x] Lining figures based on main ones + spacing + kerning
- [x] Inspect the ligatures coherence with the font.
- [x] Inspect/solve `fraction` consistency with the fractions. Adjust its sidebearings.
- [x] Check, solve or report as needed the currency symbols size, weight, consistency with the font.

**OT Features**
- [x] Check OpenType features and see if all listed are valid, e.g. if `.fina` glyphs are actually ending shapes or SS are not repeated under different names.
- [x] Create Lookup for positional alternates for `fina` and `init` cases. [Luxurious as reference case](https://github.com/googlefonts/luxurious/tree/master/sources)
- [x] All the features/classes that should be done automatically to be done in that way, e.g. `All Letters` 
- [x] Inspect if Stylistic Sets have the right name (ss01 instead of .001 etc) glyphs and generate the automatic OpenType code.
- [x] Check if there any Stylistic Set should be treated as any other feature, e.g. `SmallCaps` or `osf`.
- [x] Check if the OpenType code has any error. Hit the `update` & `compile` buttons to check everything is working well.

**Testing changes**
- [ ] Inspect the font created by the CI GHA to check production errors. If the action isn't included yet in the repo, export and test the font using Glyphs.
- [ ] Check the before and after font using `gen-html diff` if needed (for update font cases)
- [ ] Check the font on `gen-html proof` to see if it's working well on web. Use the `--imgs` flag to produce images.
- [ ] Commit and make PR using images.

**Comment by vv-monsalve** [comment]
- [x]  Some ligatures in Lavishly are not consistent with the font

<img width="794" alt="Screen Shot 2022-02-07 at 13 57 33" src="https://user-images.githubusercontent.com/48698976/152893715-5dd348f2-cd11-401b-9136-375c1ab7ac30.png">

- [x] `fraction` needs to be consistent with the actual fractions.
<img width="704" alt="Screen Shot 2022-02-07 at 19 16 39" src="https://user-images.githubusercontent.com/48698976/152893986-3013e969-1d7b-445e-a102-7d6805e1abd3.png">

**Comment by vv-monsalve** [comment]
Hi @Fonthausen,

Please take the latest file in the master branch and check the following

- [x] On the file at commit 561d188c8a65ef75b0bd92a9aac605119beff9cc the issues of the above fraction comment is still present.

**Comment by Fonthausen** [comment]
Font is ready for review
